import type { HotelDetails } from "./HotelCard";

export const mockHotelDetails: HotelDetails[] = [
  {
    id: "1",
    name: { ar: "فندق النيل الذهبي", en: "Golden Nile Hotel" },
    location: { ar: "القاهرة", en: "Cairo" },
    roomType: "hotel",
    stars: 4,
    image: "/image/hotels/hotel1.jpg",
    pricePerNight: 2200,
    amenities: ["luggageRoom", "liftAccess", "breakfast", "reception24", "hotelSafe"],
    images: ["/image/hotels/hotel1.jpg"],
    facilities: ["luggageRoom", "liftAccess", "breakfast", "reception24", "hotelSafe"],
    rooms: [
      {
        id: "r1-1",
        name: { ar: "غرفة ديلوكس — إطلالة على المدينة", en: "Deluxe — City View" },
        sizeSqm: 32,
        bedType: { ar: "1× سرير كينج", en: "1× King Bed" },
        maxGuests: 2,
        basePrice: 2200,
        breakfastPrice: 2600,
        freeCancellation: true,
      },
      {
        id: "r1-2",
        name: { ar: "جناح عائلي", en: "Family Suite" },
        sizeSqm: 45,
        bedType: { ar: "2× سرير كوين", en: "2× Queen Bed" },
        maxGuests: 4,
        basePrice: 3200,
        breakfastPrice: 3700,
        freeCancellation: false,
      },
    ],
  },
  {
    id: "2",
    name: { ar: "شاليه الساحل", en: "Coast Chalet" },
    location: { ar: "الساحل الشمالي", en: "North Coast" },
    roomType: "chalet",
    stars: 5,
    image: "/image/hotels/hotel2.jpg",
    pricePerNight: 3500,
    amenities: ["liftAccess", "restaurant"],
    images: ["/image/hotels/hotel2.jpg"],
    facilities: ["liftAccess", "restaurant"],
    rooms: [
      {
        id: "r2-1",
        name: { ar: "شاليه إطلالة بحر", en: "Sea View Chalet" },
        sizeSqm: 60,
        bedType: { ar: "2× سرير كوين", en: "2× Queen Bed" },
        maxGuests: 4,
        basePrice: 3500,
        breakfastPrice: null,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "3",
    name: { ar: "منتجع البحر الأحمر", en: "Red Sea Resort" },
    location: { ar: "الغردقة", en: "Hurghada" },
    roomType: "resort",
    stars: 5,
    image: "/image/hotels/hotel3.jpg",
    pricePerNight: 4800,
    amenities: ["swimmingPool", "beachfront", "breakfast", "wifi", "spa"],
    images: ["/image/hotels/hotel3.jpg"],
    facilities: ["swimmingPool", "beachfront", "breakfast", "wifi", "spa"],
    rooms: [
      {
        id: "r3-1",
        name: { ar: "غرفة ديلوكس — إطلالة على البحر", en: "Deluxe — Sea View" },
        sizeSqm: 38,
        bedType: { ar: "1× سرير كينج", en: "1× King Bed" },
        maxGuests: 2,
        basePrice: 4800,
        breakfastPrice: 5400,
        freeCancellation: true,
      },
      {
        id: "r3-2",
        name: { ar: "جناح سبا", en: "Spa Suite" },
        sizeSqm: 55,
        bedType: { ar: "1× سرير كينج", en: "1× King Bed" },
        maxGuests: 3,
        basePrice: 6200,
        breakfastPrice: 6800,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "4",
    name: { ar: "أجنحة الأهرامات الملكية", en: "Pyramids Royal Suites" },
    location: { ar: "الجيزة", en: "Giza" },
    roomType: "hotel",
    stars: 4,
    image: "/image/hotels/hotel4.jpg",
    pricePerNight: 1950,
    amenities: ["freeParking", "airportShuttle", "reception24", "breakfast"],
    images: ["/image/hotels/hotel4.jpg"],
    facilities: ["freeParking", "airportShuttle", "reception24", "breakfast"],
    rooms: [
      {
        id: "r4-1",
        name: { ar: "غرفة إطلالة أهرامات", en: "Pyramids View Room" },
        sizeSqm: 30,
        bedType: { ar: "1× سرير كوين", en: "1× Queen Bed" },
        maxGuests: 2,
        basePrice: 1950,
        breakfastPrice: 2300,
        freeCancellation: false,
      },
    ],
  },
  {
    id: "5",
    name: { ar: "نزل أصيلة النوبي", en: "Asala Nubian Lodge" },
    location: { ar: "أسوان", en: "Aswan" },
    roomType: "hotel",
    stars: 3,
    image: "/image/hotels/hotel5.jpg",
    pricePerNight: 1200,
    amenities: ["riverView", "breakfast", "restaurant", "airConditioning"],
    images: ["/image/hotels/hotel5.jpg"],
    facilities: ["riverView", "breakfast", "restaurant", "airConditioning"],
    rooms: [
      {
        id: "r5-1",
        name: { ar: "غرفة إطلالة النيل", en: "Nile View Room" },
        sizeSqm: 26,
        bedType: { ar: "1× سرير كوين", en: "1× Queen Bed" },
        maxGuests: 2,
        basePrice: 1200,
        breakfastPrice: 1450,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "6",
    name: { ar: "فندق البوسيت الشاطئي", en: "Beau Site Beach Hotel" },
    location: { ar: "مرسى مطروح", en: "Marsa Matrouh" },
    roomType: "hotel",
    stars: 4,
    image: "/image/hotels/hotel6.jpg",
    pricePerNight: 2800,
    amenities: ["beachfront", "swimmingPool", "liftAccess", "restaurant"],
    images: ["/image/hotels/hotel6.jpg"],
    facilities: ["beachfront", "swimmingPool", "liftAccess", "restaurant"],
    rooms: [
      {
        id: "r6-1",
        name: { ar: "غرفة إطلالة شاطئ", en: "Beachfront Room" },
        sizeSqm: 34,
        bedType: { ar: "2× سرير توين", en: "2× Twin Bed" },
        maxGuests: 3,
        basePrice: 2800,
        breakfastPrice: 3200,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "7",
    name: { ar: "كامب سحر دهب", en: "Dahab Magic Camp" },
    location: { ar: "دهب", en: "Dahab" },
    roomType: "hotel",
    stars: 3,
    image: "/image/hotels/hotel7.jpg",
    pricePerNight: 850,
    amenities: ["wifi", "petFriendly", "beachfront"],
    images: ["/image/hotels/hotel7.jpg"],
    facilities: ["wifi", "petFriendly", "beachfront"],
    rooms: [
      {
        id: "r7-1",
        name: { ar: "كوخ إطلالة بحر", en: "Sea View Hut" },
        sizeSqm: 18,
        bedType: { ar: "1× سرير مزدوج", en: "1× Double Bed" },
        maxGuests: 2,
        basePrice: 850,
        breakfastPrice: null,
        freeCancellation: true,
      },
    ],
  },
];